name: Greeting Hhw

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'The username of the user'
        required: true
      favorite_color:
        description: 'The favorite color of the user'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output-username.outputs.username }}
      favorite_color: ${{ steps.output-username.outputs.favorite_color }}
    steps:
      - name: Output Inputs
        id: output-username
        run: |
          echo "username=${{ github.event.inputs.username }}" >> $GITHUB_ENV
          echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output from job 1
        id: generate-greeting
        run: |
          GREETING="Hello, ${{ needs.job1.outputs.username }}! Your favorite color is ${{ needs.job1.outputs.favorite_color }}"
          echo "GREETING=$GREETING" >> $GITHUB_ENV

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo greeting from job 2
        run: |
          echo "${{ needs.job2.outputs.GREETING }}"